# Generated by Django 6.0.2 on 2026-05-06 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JefeInmediato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
            ],
            options={
                'verbose_name': 'Jefe Inmediato',
                'verbose_name_plural': 'Jefes Inmediatos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula No')),
                ('nombres', models.CharField(max_length=200, verbose_name='Nombres')),
                ('cargo', models.CharField(max_length=200, verbose_name='Cargo')),
                ('empresa', models.CharField(choices=[('CARBOINSA', 'CARBOINSA S.A.S.'), ('INCARSA', 'INCARSA S.A.S.'), ('UNIMINAS', 'UNIMINAS'), ('MILPA', 'MILPA S.A.S.')], max_length=20, verbose_name='Empresa')),
                ('celular', models.CharField(max_length=20, verbose_name='No Celular')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('alerta_30_enviada', models.BooleanField(default=False, verbose_name='Alerta 30 días enviada')),
                ('alerta_50_enviada', models.BooleanField(default=False, verbose_name='Alerta 50 días enviada')),
                ('evaluacion_30_completada', models.BooleanField(default=False, verbose_name='Evaluación 30 días completada')),
                ('evaluacion_50_completada', models.BooleanField(default=False, verbose_name='Evaluación 50 días completada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jefe_inmediato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores', to='_periodo_de_prueba.jefeinmediato', verbose_name='Jefe Inmediato')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['fecha_ingreso', 'nombres'],
            },
        ),
    ]
