# Generated by Django 6.0.2 on 2026-05-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_periodo_de_prueba', '0002_fix_jefe'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='resultado_periodo',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobó'), ('no_aprobado', 'No Aprobó')], default='pendiente', max_length=20, verbose_name='Resultado Periodo de Prueba'),
        ),
    ]
